#!/usr/bin/env bash
# Script: 1-list_your_processes
# Description: Display a list of currently running processes.

# Use ps command to list all processes, including those without a TTY, and format the output
ps aux --forest
