#!/usr/bin/env bash
# Script: 4-to_infinity_and_beyond
# Description: Displays "To infinity and beyond" indefinitely with a 2-second pause between each iteration.

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
