#!/usr/bin/env bash
# This script displays the content of the current directory
# Only the part of the name after the first dash is displayed

# Loop through files in the current directory
for file in *; do
    # Check if the file is not hidden and is a regular file
    if [[ ! $file == .* && -f $file ]]; then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
