#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

# Use 'ip' command to list all active IPv4 addresses
ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1
